"""empty message

Revision ID: 127bb41ff7d6
Revises: 
Create Date: 2024-09-02 22:01:48.185410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127bb41ff7d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_fullname', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('breed',
    sa.Column('breed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breed_name', sa.String(length=255), nullable=False),
    sa.Column('breed_category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('breed_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('category_picture', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_address', sa.String(length=255), nullable=False),
    sa.Column('customer_password', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_email')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_total', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_picture', sa.String(length=255), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled'), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.breed_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('order_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date_pay', sa.String(length=255), nullable=False),
    sa.Column('pay_ref', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('order_item')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customer')
    op.drop_table('categories')
    op.drop_table('breed')
    op.drop_table('admin')
    # ### end Alembic commands ###
