"""empty message

Revision ID: 432e799234cd
Revises: 5a7c6c603c3b
Create Date: 2024-09-08 00:50:28.485818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432e799234cd'
down_revision = '5a7c6c603c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
