"""empty message

Revision ID: 471748f78eee
Revises: 5819fca42b8f
Create Date: 2024-09-07 18:43:01.151243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '471748f78eee'
down_revision = '5819fca42b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.drop_column('breed_category')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'breed', ['breed_id'], ['breed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('breed_id')

    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_category', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
