"""empty message

Revision ID: 5819fca42b8f
Revises: ef0a6b9a0090
Create Date: 2024-09-07 18:32:19.963247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5819fca42b8f'
down_revision = 'ef0a6b9a0090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category_picture')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_total',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_total',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_picture', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
