"""empty message

Revision ID: 5a7c6c603c3b
Revises: 471748f78eee
Create Date: 2024-09-07 18:47:38.038876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a7c6c603c3b'
down_revision = '471748f78eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_ibfk_1', type_='foreignkey')
        batch_op.drop_column('breed_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('categories_ibfk_1', 'breed', ['breed_id'], ['breed_id'])

    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
